
main:
  - identifier: articles
    name: articles
    url: /articles
    weight: 10
  - identifier: tags
    name: tags
    url: /tags
    weight: 20
  - identifier: search
    url: /search
    name: search
    weight: 30