
main:
  - identifier: articles
    name: articles
    url: /articles
    weight: 10
  - identifier: utilitaires
    name: utilitaires
    url: /utilities
    weight: 15
  - identifier: tags
    name: tags
    url: /tags
    weight: 20
  - identifier: recherche
    name: recherche
    url: /recherche
    weight: 30